repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
    - id: black-jupyter
      types: [jupyter]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-isort
      name: isort (nbqa)
      additional_dependencies: [isort]
    - id: nbqa-pyupgrade
      name: pyupgrade (nbqa)
      args: [--py310-plus]
      additional_dependencies: [pyupgrade]
    # - id: nbqa-flake8  # doesn't work well with notebooks, disabling for now
    #   name: flake8 (nbqa)
    #   additional_dependencies: [flake8, flake8-pyproject]
- repo: https://github.com/fastai/nbdev
  rev: 2.3.32
  hooks:
    - id: nbdev_clean
    - id: nbdev_export
- repo: https://github.com/pycqa/flake8
  rev: 7.1.2
  hooks:
    - id: flake8  # Run only for specific codes
      args: [
        --max-line-length=120, 
        --per-file-ignores=__init__.py:F401,  # Doesn't raise 'import unused' error in __init__.py files
        --select=F401
      ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: debug-statements
    - id: pretty-format-json
      args: [--autofix, --indent=4]
      files: '\.json$'