repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black-jupyter
      types: [jupyter]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-isort
      name: isort (nbqa)
      additional_dependencies: [isort]
    - id: nbqa-pyupgrade
      name: pyupgrade (nbqa)
      args: [--py310-plus]
      additional_dependencies: [pyupgrade]
    # - id: nbqa-flake8  # doesn't work well with notebooks, disabling for now
    #   name: flake8 (nbqa)
    #   additional_dependencies: [flake8, flake8-pyproject]
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
    - id: nbdev_clean
    - id: nbdev_export
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: debug-statements
    - id: pretty-format-json
      args: [--autofix, --indent=4]
      files: '\.json$'