# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/schedulers/03_decaying_sine.ipynb.

# %% auto 0
__all__ = ['DecayingSineScheduler', 'DecayingSineLR']

# %% ../../nbs/schedulers/03_decaying_sine.ipynb 2
import math

from torch.optim.lr_scheduler import LRScheduler

# %% ../../nbs/schedulers/03_decaying_sine.ipynb 5
class DecayingSineScheduler:
    def __init__(self, start_value: float, max_value: float, wavelength: float, decay: float):
        assert 0.0 <= decay < 1.0, "Decay must be between 0 and 1"

        self.start_value = start_value
        self.max_value = max_value
        self.wavelength = wavelength
        self.decay_factor = 1 - decay

        self.pseudo_max_value = max_value / (self.decay_factor**0.5)

        self.x = 1

    def get(self):
        # Calculate angle based on current step and wavelength and get sine value
        angle = (-0.5 + 2 * self.x / self.wavelength) * math.pi
        sine = math.sin(angle)

        # Scale it to the range of pseudo_max_lr and max_lr
        scaled = (self.pseudo_max_value - self.start_value) * (1 + sine) / 2

        # Apply decay to it
        decayed = scaled * self.decay_factor ** ((self.x + 1) / self.wavelength)

        # Increase it by the start_lr
        lr = decayed + self.start_value

        return lr

    def step(self):
        self.x = self.x + 1

# %% ../../nbs/schedulers/03_decaying_sine.ipynb 7
class DecayingSineLR(LRScheduler):
    def __init__(self, optimizer, start_lr, max_lr, wavelength, decay, last_epoch=-1, verbose="deprecated"):
        self.scheduler = DecayingSineScheduler(start_lr, max_lr, wavelength, decay)
        self.scheduler.x -= 1  # To match the output of the non-LR scheduler
        super().__init__(optimizer, last_epoch, verbose)

    def get_lr(self):
        lr = self.scheduler.get()
        return [lr for _ in self.optimizer.param_groups]

    def step(self, epoch=None):
        self.scheduler.step()
        return super().step(epoch)
