# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/transforms/monai/05_intensity.ipynb.

# %% auto #0
__all__ = ['MultiScaleIntensityRange', 'MultiScaleIntensityRanged']

# %% ../../../nbs/transforms/monai/05_intensity.ipynb #ecaf7775
from collections.abc import Hashable, Mapping, Sequence
from warnings import warn

import numpy as np
import torch
from einops import rearrange
from monai.config import KeysCollection, NdarrayOrTensor
from monai.config.type_definitions import DtypeLike
from monai.data.meta_obj import get_track_meta
from monai.transforms import MapTransform, Transform
from monai.transforms.utils_pytorch_numpy_unification import clip
from monai.utils.enums import TransformBackends
from monai.utils.type_conversion import convert_data_type, convert_to_tensor

# %% ../../../nbs/transforms/monai/05_intensity.ipynb #9f9958e1
class MultiScaleIntensityRange(Transform):
    """Apply multiple intensity windows to a 4-D ``(C, Z Y X)`` tensor and
    concatenate the results along the channel dimension.

    Each window is applied to the **full** ``(C, Z Y X)`` input, producing
    one ``(C, Z Y X)`` output per window.  The ``W_i`` outputs are
    concatenated channel-first to give ``(W_i * C, Z Y X)``.

    Each window is specified **either** by ``(a_min, a_max)`` range **or** by
    ``(window_center, window_width)`` — but not both at the same time for a
    single window.  You may freely mix styles across windows.  Per-window
    ``b_min`` / ``b_max`` control the target range (default ``0 → 1``).

    Args:
        windows: sequence of window specs.  Each element is a dict with
            **exactly one** of the following key groups:

            * ``{"a_min": …, "a_max": …}`` — explicit source range, **or**
            * ``{"window_center": …, "window_width": …}`` — centre/width
              form (converted to ``a_min = center - width/2``,
              ``a_max = center + width/2``).

            Each dict may optionally include:

            * ``"b_min"`` (default ``0.0``) — target range minimum.
            * ``"b_max"`` (default ``1.0``) — target range maximum.

        clip: whether to clip output values to ``[b_min, b_max]`` for every
            window.
        dtype: output dtype; ``None`` keeps the input dtype.
        mode: ``"concat"`` or ``"interleave"``.

            * ``"concat"`` (default): windows concatenated in order —
              ``[w0_ch0, w0_ch1, …, w1_ch0, w1_ch1, …]``
              i.e. ``(W_i * C, Z Y X)``.
            * ``"interleave"``: channels grouped per input channel —
              ``[ch0_w0, ch0_w1, …, ch1_w0, ch1_w1, …]``
              i.e. ``(C * W_i, Z Y X)``.
    """

    MODES = ("concat", "interleave")
    backend = [TransformBackends.TORCH, TransformBackends.NUMPY]

    def __init__(
        self,
        windows: Sequence[dict],
        clip: bool = True,
        dtype: DtypeLike = np.float32,
        mode: str = "concat",
    ) -> None:
        super().__init__()
        assert len(windows) > 0, "Must provide at least one window"
        assert mode in self.MODES, f"mode must be one of {self.MODES}, got '{mode}'"
        self.clip = clip
        self.dtype = dtype
        self.mode = mode
        self._windows = self._parse_windows(windows)

    # ------------------------------------------------------------------
    @staticmethod
    def _parse_windows(
        windows: Sequence[dict],
    ) -> list[dict]:
        """Normalise every window spec into ``{a_min, a_max, b_min, b_max}``."""
        parsed: list[dict] = []
        for i, w in enumerate(windows):
            has_range = "a_min" in w and "a_max" in w
            has_center = "window_center" in w and "window_width" in w
            assert has_range ^ has_center, (
                f"Window {i}: provide exactly one of "
                f"(a_min, a_max) or (window_center, window_width), "
                f"got keys {set(w.keys())}"
            )
            if has_center:
                half = w["window_width"] / 2.0
                a_min = w["window_center"] - half
                a_max = w["window_center"] + half
            else:
                a_min = w["a_min"]
                a_max = w["a_max"]

            parsed.append(
                {
                    "a_min": float(a_min),
                    "a_max": float(a_max),
                    "b_min": float(w.get("b_min", 0.0)),
                    "b_max": float(w.get("b_max", 1.0)),
                }
            )
        return parsed

    def _apply_single_window(
        self, img: NdarrayOrTensor, a_min: float, a_max: float, b_min: float, b_max: float
    ) -> NdarrayOrTensor:
        """Scale ``img`` from ``[a_min, a_max]`` → ``[b_min, b_max]``."""
        if a_max - a_min == 0.0:
            warn("Divide by zero (a_min == a_max)", Warning)
            return img - a_min + b_min

        out = (img - a_min) / (a_max - a_min)
        if (b_min is not None) and (b_max is not None):
            out = out * (b_max - b_min) + b_min
        if self.clip:
            out = clip(out, b_min, b_max)
        return out

    def __call__(self, img: NdarrayOrTensor) -> NdarrayOrTensor:
        """Apply all windows to ``img`` (must be 4-D ``(C, Z Y X)``).

        Output shape is ``(W_i * C, Z Y X)`` for ``"concat"`` mode or
        ``(C * W_i, Z Y X)`` for ``"interleave"`` mode.
        """
        img = convert_to_tensor(img, track_meta=get_track_meta())
        assert img.ndim == 4, (
            f"MultiScaleIntensityRange expects 4-D (C, Z Y X) input, " f"got {img.ndim}-D with shape {tuple(img.shape)}"
        )

        W = len(self._windows)
        C = img.shape[0]

        # Apply each window to the full (C, Z Y X) tensor → list of (C, Z Y X)
        windowed = [self._apply_single_window(img, **w) for w in self._windows]

        # Concat: (W*C, Z Y X) — [w0_ch0, w0_ch1, …, w1_ch0, w1_ch1, …]
        out = torch.cat(windowed, dim=0)
        out = convert_data_type(out, dtype=self.dtype)[0]

        if self.mode == "interleave":
            out = rearrange(out, "(W C) Z Y X -> (C W) Z Y X", C=C, W=W)

        return out


class MultiScaleIntensityRanged(MapTransform):
    """Dictionary-based wrapper of :class:`MultiScaleIntensityRange`.

    Applies multiple intensity windows to each image key and concatenates
    the results along the channel dimension.

    The input tensor for each key must be 4-D ``(C, Z Y X)``.  After
    windowing the shape becomes ``(W_i * C, Z Y X)`` (or
    ``(C * W_i, Z Y X)`` for interleave) with channel ordering controlled
    by ``mode``.

    Args:
        keys: keys of the image tensors to transform.
        windows: sequence of window spec dicts — see
            :class:`MultiScaleIntensityRange` for the format.
        clip: whether to clip to ``[b_min, b_max]``.
        dtype: output dtype; ``None`` keeps input dtype.
        mode: ``"concat"`` or ``"interleave"``.
        allow_missing_keys: if ``True``, do not raise if a key is absent.
    """

    backend = MultiScaleIntensityRange.backend

    def __init__(
        self,
        keys: KeysCollection,
        windows: Sequence[dict],
        clip: bool = True,
        dtype: DtypeLike = np.float32,
        mode: str = "concat",
        allow_missing_keys: bool = False,
    ) -> None:
        super().__init__(keys, allow_missing_keys=allow_missing_keys)
        self.scaler = MultiScaleIntensityRange(windows=windows, clip=clip, dtype=dtype, mode=mode)

    def __call__(self, data: Mapping[Hashable, NdarrayOrTensor]) -> dict[Hashable, NdarrayOrTensor]:
        d = dict(data)
        for key in self.key_iterator(d):
            d[key] = self.scaler(d[key])
        return d
